config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  get 'publics/home'
  get 'publics/profile' => 'publics/update'
  get 'publics/about'

  resources :matches
  root 'publics#home'
  get '/matches' => 'matches#index'
  post 'update' => 'publics#update'
  get 'join' => 'matches#join'
  get 'leave' => 'matches#leave'
  post '/update_skill' => 'publics#update_skill'
  post '/update_image' => 'publics#update_image'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  validate :match_date_cannot_be_in_the_past
  validates :location, presence: true

  def match_date_cannot_be_in_the_past
    if timeslot < Date.today
      errors.add(:timeslot_error, "You can't schedule a match in the past")
    end
  end

  def self.match_info
      matches = []
      all.each do |m|
        loc = Location.find_by_name(m.location)
        p loc
        if m.user2_id.blank?
          matches << {id: m.id, location: loc.name.gsub!(/_/, ' '), address: loc.address, zip: loc.zip, timeslot: m.timeslot, user2_id: m.user2_id, user_id: m.user_id, user_name: m.user.name_initial, user_skill: m.user.skill_level, user2_skill: ""}
        else
          user2 = User.find(m.user2_id)
          matches << {id: m.id, location: loc.name.gsub!(/_/, ' '), address: loc.address, zip: loc.zip, timeslot: m.timeslot, user2_id: m.user2_id, user_id: m.user_id, user_name: m.user.name_initial, user2_name: user2.name_initial, user_skill: m.user.skill_level, user2_skill: user2.skill_level}
        end
      end
      matches = matches.sort_by{|match| match[:timeslot]}
    end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :matches
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



    has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" },
    :default_url => ":style/missing.png"

    validates_attachment :image,
          content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
          size: { in: 0..10.megabytes }
    validates :first_name, presence: true
    validates :last_name, presence: true
    def name
      @name = first_name + " " + last_name
    end

    def name_initial
      @name_initial = first_name + " " + last_name[0]
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  private
  def after_sign_in_path_for(resource)
    '/matches'
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy, :join, :leave]
  before_action :authenticate_user!, except: [:destroy]
  # before_action :set_user_info, only: [:show]

  # GET /matches
  # GET /matches.json

  def show_locations
    @locations = Location.all
  end

  def index
    @matches = Match.match_info
  end

  def join
    @match.update(user2_id: params[:user2_id])
    @match.save
    redirect_to '/matches'
  end
  def leave
    @match.update(user2_id: nil)
    @match.save
    redirect_to '/matches'
  end

  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
    @google_api_key = 'AIzaSyCsAS0jtTVddtNAwYcrfDhPZziN6F620jA'
    @map_center = [32.764212, -117.162570]
    @map_zoom = 11
    @locations = Location.all
  end

  # GET /matches/1/edit
  def edit
    @google_api_key = 'AIzaSyCsAS0jtTVddtNAwYcrfDhPZziN6F620jA'
    @map_center = [32.764212, -117.162570]
    @map_zoom = 11
    @locations = Location.all
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    @locations = Location.all

    respond_to do |format|
      if @match.save
        format.html { redirect_to '/matches', notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to '/matches', notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def map

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # def set_user_info
    #   @user1_first_name = User.find(@match.user_id).first_name
    #   @user1_last_name = User.find(@match.user_id).last_name
    # end


    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:user_id, :user1_id, :user2_id, :location, :timeslot)
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def home
  end

  def about
  end

  def profile
  end

  def update_skill
    params.permit(:skill_level, :image)
    @user = current_user
    if params.has_key?(:skill_level)
      @user.update(skill_level: params[:skill_level])
      @user.save
    end
    render "profile"
  end

  def update_image
    params.permit(:skill_level, :image)
    @user = current_user
    if params.has_key?(:image)
      @user.update(image: params[:image])
      @user.save
    end
    render "profile"
  end

  private
  def user_params
    params.permit(:skill_level, :image)
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :image, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :image, :password, :password_confirmation, :current_password)
  end

  def after_update_path_for(resource)
    '/publics/profile'
  end

  def after_sign_up_path_for(resource)
    '/publics/profile'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tennis Love</title>
    <meta name="viewport" content="width=device-width">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
  </head>

  <body>
    <% if user_signed_in? %>
      <%= react_component('NavBar_signed_in')%>
    <% else %>
      <%=  react_component('NavBar') %>
    <%end%>
    <%= yield %>
      <%= react_component('Footer') %>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <input type="hidden" name="match[user_id]" value="<%= current_user.id %>">
  </div>

  <select class="form-group" name="match[location]">
    <option selected disabled="">Select Court Location</option>
    <% for location in Location.order("name") %>
    <option value=<%=location.name%>><%=location.name.gsub!(/_/, ' ')%></option>
    <% end %>
  </select>


  <div class="field">
    <%= form.label :timeslot %>
    <%= form.datetime_select :timeslot, id: :match_timeslot %>
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="Create Match" data-disable-with="Create Match" class="btn btn-primary btn-sm" />
  </div>
<% end %>

app/views/matches/calendar.html.erb
<h1>Calendar</h1>
<iframe src="https://calendar.google.com/calendar/embed?src=echogems2017%40gmail.com&ctz=America%2FLos_Angeles" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

<%= react_component("Calendar") %>

app/views/matches/edit.html.erb
<div class='body'id="new-match-body">
  <div class="new-match-box match-left split-item">
    <h1>Editing Match</h1>
    <%= render 'form', match: @match %>
    <%= link_to 'Back', matches_path %>
  </div>
  <div class="match-right split-item">
    <%= react_component("Map", {
      googleApiKey: @google_api_key,
      center: @map_center,
      zoom: @map_zoom,
      pins: @locations
      }) %>
    </div>
</div>

app/views/matches/index.html.erb
<div class='matches-body'>
  <%= react_component("MatchesIndex", {matches: @matches, current_user: current_user.id}) %>
</div>

app/views/matches/new.html.erb
<div class='body'id="new-match-body">
  <div class="new-match-box match-left split-item">
    <h1>New Match</h1>
    <%= render 'form', match: @match %>
    <%= link_to 'Back', matches_path %>
  </div>
  <div class="match-right split-item">
    <%= react_component("Map", {
      googleApiKey: @google_api_key,
      center: @map_center,
      zoom: @map_zoom,
      pins: @locations
      }) %>
    </div>
</div>

app/views/matches/show.html.erb
<div class='body'>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Player 1:</strong>
    <%= @match.user_id %>
  </p>

  <p>
    <strong>Player 2:</strong>
    <%= @match.user2_id %>
  </p>

<p>
  <strong>Location:</strong>
  <%= @match.location.gsub!(/_/, ' ') %>
</p>

  <p>
    <strong>Timeslot:</strong>
    <%= @match.timeslot %>
  </p>

  <%= link_to 'Edit', edit_match_path(@match) %> |
  <%= link_to 'Back', matches_path %>
</div>

app/views/publics/_form.html.erb
<%= form_with(model: user, local: true, multipart: true) do |f| %>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
<% end %>

app/views/publics/about.html.erb
<%=react_component('About') %>

app/views/publics/home.html.erb
<%=react_component('Home') %>

app/views/publics/profile.html.erb
<script type="text/javascript">
  function showInfo(){
    console.log("I was clicked")
    var tooltip = document.getElementById("tooltip_border")

    if(tooltip.style.display === "block"){
      tooltip.style.display = "none";
    } else {
      tooltip.style.display = "block";
    }
  }
</script>

<div id="user_profile" class='body'>
  <h1>My Profile</h1>
  <div id="user_info">
    <%= link_to image_tag(current_user.image.url(:large)), current_user.image.url %>
    <div id="user_data">
      <p><strong>First Name:</strong> <%=current_user.first_name%></p>
      <p><strong>Last Name:</strong> <%=current_user.last_name%></p>
      <p><strong>Email:</strong> <%=current_user.email%></p>
      <p><strong>Skill Level:</strong> <%=current_user.skill_level%></p>
      <form action="/update_skill" method="post" enctype="multipart/form-data">
        <div class="form-group">
          <select name= "skill_level" class="custom-select">
            <option selected disabled="skill_level">Select Skill Level</option>
            <option name= "skill_level" value="Beginner">Beginner</option>
            <option name= "skill_level" value="Intermediate">Intermediate</option>
            <option name= "skill_level" value="Advanced">Advanced</option>
          </select>
          <input class="btn btn-info btn-sm" type="submit" value="Update Skill" />
          <img src="/assets/Info.jpg" onClick="showInfo()" class="tooltip_icon" />
          <br />
          <div id="tooltip_border">
            <div class="skill_show">
              Beginner: Able to play short rallies of slow pace.
            </div>
            <div class="skill_show">
              Intermediate: Able to serve and play consistent rallies.
            </div>
            <div class="skill_show">
              Advanced: Able to serve with power and stroke accuracy.
            </div>
          </div>
        </div>
      </form>
      <form style="display:inline-block" action="/update_image" method="post" enctype="multipart/form-data">
          <p>Select your profile picture</p>
          <input class="imagefile" type="file" id="file" name="image" accept="image/*">
          <label class="btn btn-primary btn-sm" for="file">Choose File</label>
          <input class="btn btn-secondary btn-sm"type="submit" value="Update Picture">
      </form>
      <div>
        <%= link_to "Edit/Cancel Account", edit_user_registration_path %>
      </div>
      <br/>
      <br/>
    </div>
  </div>
  <div id="availability">
    <a href="/matches/new" style="text-decoration: none"><button type="button" class="btn custom-btn btn-lg btn-block">Let's play</button></a>
  </div>
</div>